# Generated by Django 5.1 on 2024-08-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested_Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('stock_img', models.FileField(default=None, max_length=250, null=True, upload_to='profile_img/')),
            ],
        ),
    ]
