# Generated by Django 5.1 on 2024-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_sec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=70)),
                ('card_discription', models.CharField(max_length=110)),
                ('card_img', models.FileField(default=None, max_length=250, null=True, upload_to='card_img/')),
            ],
        ),
    ]
