# Generated by Django 5.1 on 2024-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_other_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=70)),
                ('tamp_img', models.FileField(default=None, max_length=250, null=True, upload_to='Tamp/')),
                ('tamp_discription', models.TextField(max_length=1000)),
                ('short_discription', models.TextField(max_length=110)),
                ('step_img1', models.FileField(default=None, max_length=250, null=True, upload_to='step_img/')),
                ('step_title1', models.CharField(max_length=70)),
                ('step_discription1', models.TextField(max_length=500)),
                ('step_img2', models.FileField(default=None, max_length=250, null=True, upload_to='step_img/')),
                ('step_title2', models.CharField(max_length=70)),
                ('step_discription2', models.TextField(max_length=500)),
                ('step_img3', models.FileField(default=None, max_length=250, null=True, upload_to='step_img/')),
                ('step_title3', models.CharField(max_length=70)),
                ('step_discription3', models.TextField(max_length=500)),
                ('step_img4', models.FileField(default=None, max_length=250, null=True, upload_to='step_img/')),
                ('step_title4', models.CharField(max_length=70)),
                ('step_discription4', models.TextField(max_length=500)),
                ('step_img5', models.FileField(default=None, max_length=250, null=True, upload_to='step_img/')),
                ('step_title5', models.CharField(max_length=70)),
                ('step_discription5', models.TextField(max_length=500)),
                ('step_img6', models.FileField(default=None, max_length=250, null=True, upload_to='step_img/')),
                ('step_title6', models.CharField(max_length=70)),
                ('step_discription6', models.TextField(max_length=500)),
                ('step_img7', models.FileField(default=None, max_length=250, null=True, upload_to='step_img/')),
                ('step_title7', models.CharField(max_length=70)),
                ('step_discription7', models.TextField(max_length=500)),
                ('step_img8', models.FileField(default=None, max_length=250, null=True, upload_to='step_img/')),
                ('step_title8', models.CharField(max_length=70)),
                ('step_discription8', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='other_sec',
            name='card_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='front-img/'),
        ),
        migrations.AlterField(
            model_name='suggested_steps',
            name='stock_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='front-img/'),
        ),
    ]
